import type { NextPage } from 'next'
import Head from 'next/head'

import Layout from '../layouts/Main'

import { Box, Text } from '@chakra-ui/react'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Components by Caleb Hyatt</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Layout>
        <Text as="h1" color="white" fontSize="4xl">
          Hello World!
        </Text>
      </Layout>
    </>
  )
}

export default Home
